// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bright-mindful-pages/GentleCompanion.tsx": () => import("../components/mockups/bright-mindful-pages/GentleCompanion.tsx"),
  "./components/mockups/bright-mindful-pages/MindfulPath.tsx": () => import("../components/mockups/bright-mindful-pages/MindfulPath.tsx"),
  "./components/mockups/bright-mindful-pages/QuietWordmark.tsx": () => import("../components/mockups/bright-mindful-pages/QuietWordmark.tsx")
};
